# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  identity:
    image: identity
    build:
      context: .
      dockerfile: src/identity/Dockerfile
    ports:
      - 80